#!/bin/sh

# escapes backticks, dollar signs, double quotes, and backticks
sanitize_string () {
	cat | sed -r 's|([`$"\])|\\&|g'
}

# 0 if integer
is_int () {
	local absloute="$1"

	# remove sign
	case "$absloute" in
		-*) absloute="${1#*-}"
	esac
	
	case "$absloute" in
		''|*[!0-9]*) return 1 ;;
		*) return 0 ;;
	esac
}

# 0 if positive integer
is_pos  () {
	if ! is_int "$1"; then
		return 1
	fi

	if [ "$1" -gt 0 ]; then
		return 0
	else
		return 1
	fi
}

# splits two numbers separated by a colon
split_range () {
	# split on the colon
	index1="${1%%:*}"
	index2="${1#*:}"

	# reject bad tokens
	if ! is_int "$index1"; then
		return 1
	fi
	if ! is_int "$index2"; then
		return 1
	fi
}

# swaps index1 with index2 if the first is greater
arrange_indices () {
	# smaller index should be the first
	if [ "$index1" -gt "$index2" ]; then
		local temp="$index1"
		index1="$index2"
		index2="$temp"
	fi
}

# decorates stdin
highlight_lines () {
	if [ -t 1 ] && [ "$co_decorate" -eq 1 ]; then
		awk "{if(NR%2) print \"$co_even_decoration\"\$0; else print \"$co_odd_decoration\"\$0}"
		printf "$(tput sgr0)"
	else
		cat
	fi
}

# writes a setting of the form $2=$3 to the file $1
append_setting () {
	local lvalue="$2"
	local rvalue="\"$(echo "$3" | sanitize_string)\""
	echo "$lvalue=$rvalue" >> "$1"
}

# writes the answer variable
write_ans () {
	local co_file_ans_temp="$co_cache"/ans-temp

	echo "$1"

	# delete last line first (i.e., ans="value")
	head -n -1 "$co_file_ans" > "$co_file_ans_temp"
	mv "$co_file_ans_temp" "$co_file_ans"
	
	# append the new answer
	append_setting "$co_file_ans" "$co_ans_prefix" "$1"

	# prepend shiftings (i.e., ans2="$ans1", ans1="$ans", etc.)
	variables_count="$(wc -l "$co_file_ans" | awk '{print $1}')"
	
	if [ "$variables_count" -lt "$co_ans_max" ]; then
		if [ "$variables_count" -eq 1 ]; then
			echo "$co_ans_prefix$variables_count=\"\$$co_ans_prefix\"" | cat - "$co_file_ans" > "$co_file_ans_temp"
			mv "$co_file_ans_temp" "$co_file_ans"
		elif ! [ "$variables_count" -eq 0 ]; then 
			echo "$co_ans_prefix$variables_count=\"\$$co_ans_prefix$(expr $variables_count - 1)\"" | cat - "$co_file_ans" > "$co_file_ans_temp"
			mv "$co_file_ans_temp" "$co_file_ans"
		fi
	fi

	touch "$co_file_ans_dirt"
}

load_configuration () {

	# if no path for co cache is specified, default to ~/.co
	if ! [ -n "$co_cache" ]; then
		co_cache="$HOME"/.co
	fi

	# set files names
	co_file_lines="$co_cache"/populate.sh
	co_file_ans="$co_cache"/ans.sh
	co_file_buffer="$co_cache"/output
	co_file_conf="$co_cache"/conf
	co_file_lines_dirt="$co_cache"/dirt
	co_file_ans_dirt="$co_cache"/ans-dirt
	co_file_hooks_conf="$co_cache"/hooks-conf.sh

	mkdir -p "$co_cache"
	touch "$co_file_ans" "$co_file_lines" "$co_file_buffer" "$co_file_conf"

	# default configuration
	co_lines_max=50
	co_lines_prefix=l
	co_ans_prefix=ans
	co_ans_max=10
	co_even_decoration="$(tput bold)"
	co_odd_decoration="$(tput sgr0)"
	co_decorate=1
	co_on_ans=""

	# override default configuration
	. "$co_file_conf"

	# some of the previous variables are needed by co-hooks.*
	> "$co_file_hooks_conf"
	append_setting "$co_file_hooks_conf" "co_on_ans" "$co_on_ans"

}

handle_stdin () {
	# stdin
	if ! [ -t 0 ]; then
		# if no arguments are provided, pipe the output to the user also,
		# otherwise just write the buffer to a file and leave the argumetns to
		# be handled later
		if [ "$#" -eq 0 ]; then
			tee "$co_file_buffer" | nl -ba | highlight_lines
		else
			cat > "$co_file_buffer"
		fi

		# --- exporting line variables --- #
		
		# <prefix><line_nr>="<sanitized_line>"

		# consider the first n lines only (speicified by configuration)
		head -n$co_lines_max "$co_file_buffer" | \
		# escape backticks, dollar signs, double quotes and backslashes
		sanitize_string | \
		# enclose in double quotes and prepend an equal sign
		sed 's|\(.*\)|="\1"|g' | \
		# prepend line number
		awk '{printf("%d%s\n", NR, $0)}' | \
		# prepend prefix
		sed -e "s/^/$co_lines_prefix/" > "$co_file_lines"
		# raise the dirty flag (that sounds like an idiom (but it isn't))
		touch "$co_file_lines_dirt"

		# --- done exporting first n line variables --- #
	fi
}

handle_args () {
	# co help
	if [ "$#" -eq 1 ] && [ "$1" = help ]; then
		cat "$(dirname $(which co))/../README" | less
	
	# co clear
	elif [ "$#" -eq 1 ] && [ "$1" = clear ]; then
		# evacuate the double quotes
		sed -i -e 's/".*$/""/g' "$co_file_lines"
		sed -i -e 's/".*$/""/g' "$co_file_ans"
		
		# empty the buffer
		> "$co_file_buffer"

		# raise dirty flag
		touch "$co_file_lines_dirt"
		touch "$co_file_ans_dirt"
		append_setting "$co_file_hooks_conf" "co_clear" 1

	# co
	elif [ "$#" -eq 0 ] && [ -t 0 ]; then
		nl -ba "$co_file_buffer" | highlight_lines

	# co
	elif [ "$#" -eq 0 ] && ! [ -t 0 ]; then
		# already printed
		true

	# co J
	elif [ "$#" -eq 1 ] && is_pos "$1"; then
		local ans="$(tail -n "+$1"  "$co_file_buffer" | head -n 1)"
		write_ans "$ans"
	
	# co J K
	elif [ "$#" -eq 2 ] && is_pos "$1" && is_int "$2"; then
		local awkparam=$2

		# handle words of negative index
		if [ "$awkparam" -lt 0 ]; then
			awkparam="(NF+1$2)"
		fi

		local ans=$(tail -n "+$1"  "$co_file_buffer" | head -n 1 | awk  "{print \$$awkparam}")
		write_ans "$ans"

	# co J:K
	elif [ "$#" = 1 ] && split_range "$1"; then
		arrange_indices
		awk "NR==$index1, NR==$index2" "$co_file_buffer"

	# co J K:L
	elif test "$#" -eq "2" && is_pos "$1" && split_range "$2"; then
		local line="$(tail -n "+$1" "$co_file_buffer" | head -n 1)"
		local words_count="$(echo "$line" | awk '{print NF}')"

		if [ "$index1" -lt 0 ]; then
			index1="$(expr $index1 + $words_count + 1)"
		fi

		if [ "$index2" -lt 0 ]; then
			index2="$(expr $index2 + $words_count + 1)"
		fi
		
		arrange_indices

		local ans="$(echo $line | awk "{ split(\$0, a, \"\\\\s+\", s); for (i = $index1; i <= $index2 && i <= length(a); i++) printf \"%s%s\", a[i], (i < $index2 ? s[i] : \"\\n\") }")"
		write_ans "$ans"
	else
		exit 1
	fi
}

main () {
	# notify the interactive shell when we exit so it handles our variables
	trap "kill -CONT $PPID" TERM EXIT INT

	load_configuration
	handle_stdin "$@"
	handle_args "$@"
}

main "$@"

